//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEnterprise.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendence
    {
        public int AttendenceID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Dated { get; set; }
        public bool State { get; set; }
        public decimal MinutesSpend { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
