//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEnterprise.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendences = new HashSet<Attendence>();
            this.DepartmentEmployeeRelations = new HashSet<DepartmentEmployeeRelation>();
        }
    
        public int EmployeeID { get; set; }
        public string EmpoyeeName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public short EmployeeCategoryID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual ICollection<DepartmentEmployeeRelation> DepartmentEmployeeRelations { get; set; }
        public virtual EmployeeCategory EmployeeCategory { get; set; }
    }
}
